### ISSUE TITLE
Fix navigation menu responsivity in homepage

### ISSUE THREAD

**Issue by mateuseap** [mateuseap/mateuseap.github.io#6]
Navigation menu is not responsive. When the page size shrinks the menu buttons start overlapping.

**Comment by Aniumbott** [comment]
Hello, can I work on this?, I will turn it into a burger menu button.

**Comment by mateuseap** [comment]
@Aniumbott for sure! Go ahead :)

**Comment by Aniumbott** [comment]
I've created a pull request regarding this issue, do add **hacktoberfest-accepted** if you like it. 🙌

**Comment by mateuseap** [comment]
Thank you so much for contributing! I added the Hacktoberfest tags, hope it count towards your progress there :)
