### ISSUE TITLE
Fix homepage text responsivity

### ISSUE THREAD

**Issue by mateuseap** [mateuseap/mateuseap.github.io#7]
When the homepage starts to shrink the welcome text goes off the viewport and breaks everything resulting in a white border on the end of the page.

**Comment by Chaitanya-087** [comment]
hi ! would like work on this

**Comment by mateuseap** [comment]
@Chaitanya-087 feel free to do it! :)

**Comment by Gulshan-11** [comment]
Hi I would like to work on this

**Comment by mateuseap** [comment]
@Gulshan-11 feel free to work on it! I can assign you the task if you want :]

**Comment by Gulshan-11** [comment]
Yeah please assign it to me.
