### ISSUE TITLE
Fix navigation menu responsivity in `About me` and `Projects` pages

### ISSUE THREAD

**Issue by mateuseap** [mateuseap/mateuseap.github.io#9]
## Issue description

The navigation menu responsivity was fixed in issue #6 by PR #8, but the pages `About me` and `Projects` still have de old non-responsive navigation menu.

## Tips

You can simply reproduce what was made in PR #8 and add the new burger menu to these pages :)

**Comment by najeebkp** [comment]
Hi @mateuseap please assign this to me

**Comment by mateuseap** [comment]
@najeebkp feel free to contribute! :)

**Comment by mateuseap** [comment]
@najeebkp I'll review your PR as soon as possible!
